export const ADD_HEALTHFACILITY_REQUEST = 'ADD_HEALTHFACILITY_REQUEST';
export const ADD_HEALTHFACILITY_SUCCESS = 'ADD_HEALTHFACILITY_SUCCESS';
export const ADD_HEALTHFACILITY_FAILURE = 'ADD_HEALTHFACILITY_FAILURE';