export const APPROVED_SCHOOLS_REQUEST = 'APPROVED_SCHOOLS_REQUEST';
export const APPROVED_SCHOOLS_SUCCESS = 'APPROVED_SCHOOLS_SUCCESS';
export const APPROVED_SCHOOLS_FAILURE = 'APPROVED_SCHOOLS_FAILURE';