export const HEALTHFACILITIES_REQUEST = 'HEALTHFACILITIES_REQUEST';
export const HEALTHFACILITIES_SUCCESS = 'HEALTHFACILITIES_SUCCESS';
export const HEALTHFACILITIES_FAILURE = 'HEALTHFACILITIES_FAILURE';