export const REJECTED_SCHOOLS_REQUEST = 'REJECTED_SCHOOLS_REQUEST';
export const REJECTED_SCHOOLS_SUCCESS = 'REJECTED_SCHOOLS_SUCCESS';
export const REJECTED_SCHOOLS_FAILURE = 'REJECTED_SCHOOLS_FAILURE';